AssessEEZ/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users.views import (
    login_view, learner_view, eqa_view, iqa_view,
    assessor_view, administrator_view, contact_view,
    pricing_view, privacy_policy_view, user_agreement_view, faq_view
)
from django.views.generic import TemplateView
from django.http import HttpResponse

def health_check(request):
    return HttpResponse("OK", content_type="text/plain")

urlpatterns = [
    path('health/', health_check, name='health_check'),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('qualifications/', include(('qualifications.urls', 'qualifications'), namespace='qualifications')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('login/', login_view, name='login'),
    path('learner/', learner_view, name='learner'),
    path('eqa/', eqa_view, name='eqa'),
    path('iqa/', iqa_view, name='iqa'),
    path('assessor/', assessor_view, name='assessor'),
    path('administrator/', administrator_view, name='administrator'),
    path('contact/', contact_view, name='contact'),
    path('captcha/', include('captcha.urls')),
    path('pricing/', pricing_view, name='pricing'),
    path('privacy_policy/', privacy_policy_view, name='privacy_policy'),
    path('user_agreement/', user_agreement_view, name='user_agreement'),
    path('faq/', faq_view, name='FAQ'),
    path('api/', include('stripe_payments.urls')),
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   # Serve static files from STATICFILES_DIRS during development
   from django.contrib.staticfiles.urls import staticfiles_urlpatterns
   urlpatterns += staticfiles_urlpatterns()

#if settings.DEBUG:
 #   import debug_toolbar
  #  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   # urlpatterns += [
    #    path('__debug__/', include(debug_toolbar.urls)),
    #]

qualifications/urls.py
from django.urls import path
from . import views


app_name = 'qualifications'

urlpatterns = [
    path('qualifications/', views.QualificationAddEditView.as_view(), name='qualification-list'),
    path('<uuid:qualification_id>/', views.QualificationAddEditView.as_view(), name='qualification-detail'),
    path('qualifications/search/', views.QualificationSearchView.as_view(), name='qualification-search'),
    path('add/api/', views.QualificationAddEditView.as_view(), name='add-qualification-api'),
    path('add/', views.render_add_qualification_view, name='add-qualification'),
    path('edit/<uuid:qualification_id>/', views.QualificationAddEditView.as_view(), name='edit-qualification'), 
    path('edit/', views.edit_qualification_view, name='edit-qualification-html'),  
    path('view/', views.view_qualification_view, name='view-qualification'),
    path('list/', views.QualificationListView.as_view(), name='qualification-list'),
    path('add_user/', views.add_user_role_select, name='add_user'),
    path('add_learner/', views.add_learner, name='add_learner'),
    path('add_assessor/', views.add_assessor, name='add_assessor'),
    path('add_iqa/', views.add_iqa, name='add_iqa'),
    path('add_eqa/', views.add_eqa, name='add_eqa'),
    path('get_learners/', views.get_learners, name='get_learners'),
    path('get_assessors/', views.get_assessors, name='get_assessors'),
    path('get_iqas/', views.get_iqas, name='get_iqas'),
    path('current-users/', views.current_users, name='current_users'),
    path('selected_user/<int:user_id>/<str:role_type>/', views.selected_user, name='selected_user'),
    path('toggle_learner_access/', views.toggle_learner_access, name='toggle_learner_access'),
    path('delete-learner-qualification/', views.delete_learner_qualification, name='delete_learner_qualification'),
    path('edit-user-search/', views.edit_user_search, name='edit_user_search'),
    path('search-users/', views.search_users, name='search_users'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('remove-role-qualification/', views.remove_role_qualification, name='remove_role_qualification'),
    path('change_learner_assessor/', views.change_learner_assessor, name='change_learner_assessor'),
    path('change-learner-iqa/', views.change_learner_iqa, name='change_learner_iqa'),
    path('resources/', views.resources, name='resources'),
    path('resources/folder/<uuid:folder_id>/', views.folder_detail, name='folder_detail'),
    path('resources/add_folder/', views.add_folder, name='add_folder'),
    path('resources/delete_file/', views.delete_file, name='delete_file'),
    path('resources/file/<uuid:file_id>/', views.serve_file, name='serve_file'),
    path('resources/edit_folder/<uuid:folder_id>/', views.edit_folder, name='edit_folder'),
    path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
    path('learner_view/<uuid:qualification_id>/', views.learner_view, name='learner_view'),
    path('learner_evidence/<uuid:qualification_id>/<uuid:learner_id>/<uuid:ac_id>/', views.learner_evidence_view, name='learner_evidence'),
    path('assessor/<uuid:qualification_id>/', views.assessor_view, name='assessor_view'),
    path('assessor_feedback/<uuid:qualification_id>/<uuid:learner_id>/', views.assessor_feedback_view, name='assessor_feedback'),
    path('feedback_history/<uuid:qualification_id>/<uuid:learner_id>/<uuid:lo_id>/', views.feedback_history_view, name='feedback_history'),
    path('notifications/', views.notification_view, name='notification_view'),
    path('iqa/<uuid:qualification_id>/', views.iqa_view, name='iqa_view'),
    path('iqa/<uuid:qualification_id>/learner/<uuid:learner_id>/feedback/', views.iqa_feedback_history_view, name='iqa_feedback_history_view'),
    path('iqa/<uuid:qualification_id>/learner/<uuid:learner_id>/unit/<uuid:unit_id>/feedback/', views.iqa_feedback_view, name='iqa_feedback'),
    path('iqa/<uuid:qualification_id>/learner/<uuid:learner_id>/unit/<uuid:unit_id>/feedback_history/', views.iqa_feedback_history, name='iqa_feedback_history'),
    path('iqa/<uuid:qualification_id>/feedback_to_assessor/', views.iqa_feedback_to_assessor_view, name='iqa_feedback_to_assessor'),
    path('iqa/<uuid:qualification_id>/feedback_to_assessor_records/', views.iqa_feedback_to_assessor_records_view, name='iqa_feedback_to_assessor_records'),
    path('iqa/feedback_to_assessor_records/', views.iqa_feedback_to_assessor_records_view, name='iqa_feedback_to_assessor_records'),
    path('doc_requirement/', views.doc_requirement, name='doc_requirement'),
    path('submit_docs/<uuid:qualification_id>/', views.submit_docs, name='submit_docs'),  
    path('doc_check/<uuid:qualification_id>/<uuid:learner_id>/', views.doc_check, name='doc_check'), 
    path('iqa_submitted_docs/<uuid:qualification_id>/<uuid:learner_id>/', views.iqa_submitted_docs, name='iqa_submitted_docs'),
    path('eqa/<uuid:qualification_id>/<uuid:learner_id>/', views.eqa_view, name='eqa_view'),
    path('eqa_learners/<uuid:qualification_id>/', views.eqa_learner_list, name='eqa_learner_list'),
    path('learners_list/<int:user_business_id>/<str:role_type>/<uuid:qualification_id>/', views.learners_list, name='learners_list'),
    path('iqa_sub_doc_for_eqa/<uuid:qualification_id>/<uuid:learner_id>/', views.iqa_sub_doc_for_eqa, name='iqa_sub_doc_for_eqa'),
    path('qualification/<uuid:qualification_id>/learner_specific_docs/<uuid:learner_id>/', views.learner_specific_docs, name='learner_specific_docs'),
    path('qualification/<uuid:qualification_id>/learner_specific_docs/<uuid:learner_id>/edit/<uuid:doc_id>/', views.edit_learner_doc, name='edit_learner_doc'),
    path('qualification/<uuid:qualification_id>/learner_specific_docs/<uuid:learner_id>/delete/<uuid:doc_id>/', views.delete_learner_doc, name='delete_learner_doc'),
    path('learner_resources/<uuid:qualification_id>/', views.learner_resources_view, name='learner_resources'),
    path('assessor_resources/<uuid:qualification_id>/', views.assessor_resources_view, name='assessor_resources'),
    path('iqa_resources/<uuid:qualification_id>/', views.iqa_resources_view, name='iqa_resources'),
    path('eqa_resources/<uuid:qualification_id>/', views.eqa_resources_view, name='eqa_resources'),
    path('inbox/', views.inbox_view, name='inbox'),
    path('compose/', views.compose_message_view, name='compose_message'),
    #path('thread/<str:subject>/', views.message_thread_view, name='message_thread'),
    #path('thread/<path:subject>/', views.message_thread_view, name='message_thread'),
    path('thread/<uuid:thread_id>/', views.message_thread_view, name='message_thread'),
    path('mark-read/', views.mark_message_read_view, name='mark_message_read'),
    path('get-recipients/', views.get_recipients_by_qualification, name='get_recipients_by_qualification'),
    path('assessor/<uuid:qualification_id>/feedback/<uuid:learner_id>/<uuid:lo_id>/provide/', views.provide_feedback, name='provide_feedback'),
    path('sent/', views.sent_messages_view, name='sent_messages'),
    ]

users/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenRefreshView
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('superadmin/', views.superadmin_view, name='superadmin'),
    path('create_admin/', views.create_admin_view, name='create_admin'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('create_user/', views.create_user_view, name='create_user'),
    path('forgot_password/', views.forgot_password_view, name='forgot_password'),
    path('reset_password/<str:uidb64>/<str:token>/', views.reset_password_view, name='reset_password'),
    path('api/token/', views.CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', RedirectView.as_view(pattern_name='login'), name='home'),
    path('logout/', views.custom_logout_view, name='custom_logout'),
    path('business/<str:business_id>/', views.business_details, name='business_details'),
    path('business/<str:business_id>/<str:role>/<str:period>/', views.admin_users_details, name='admin_users_details'),
    path('add_logo/', views.add_logo_view, name='add_logo'),
    path('password-reset-redirect/<str:uidb64>/<str:token>/', views.password_reset_redirect, name='password_reset_redirect'),
    path('superadmin/assign/<uuid:qual_id>/', views.assign_qualification, name='assign_qualification'),
    path('superadmin/dashboard/', views.superadmin_qualifications_dashboard, name='superadmin_qualifications_dashboard'),
    path('main/', views.main_page, name='main_page'),
    path('select_business/', views.select_business, name='select_business'),
]

users/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
import uuid
from storages.backends.s3boto3 import S3Boto3Storage


class CustomUserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, **extra_fields)

class Business(models.Model):
    business_id = models.CharField(max_length=6, primary_key=True, editable=False)
    name = models.CharField(max_length=255)
    address = models.TextField()
    website = models.URLField(blank=True, null=True)
    logo = models.ImageField(upload_to='business_logos/%Y/%m/%d/', storage=S3Boto3Storage(), blank=True, null=True)  # Updated
    created_at = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        if not self.business_id:
            last_business = Business.objects.order_by('-business_id').first()
            if not last_business:
                self.business_id = 'AA0001'
            else:
                last_id = last_business.business_id
                prefix = last_id[:2]
                number = int(last_id[2:])
                if number < 9999:
                    self.business_id = prefix + f"{number + 1:04d}"
                else:
                    num = (ord(prefix[0]) - ord('A')) * 26 + (ord(prefix[1]) - ord('A'))
                    if num >= 675:
                        raise ValueError("No more business IDs available")
                    next_prefix = chr((num + 1) // 26 + ord('A')) + chr((num + 1) % 26 + ord('A'))
                    self.business_id = next_prefix + '0001'
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name



class CustomUser(AbstractUser):
    email = models.EmailField(unique=True, blank=False, null=False)  # Unique globally
    username = None  # Remove username
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    full_name = models.CharField(max_length=255, blank=True, null=True)

    objects = CustomUserManager()  # Assign custom manager

    def __str__(self):
        return self.email



class UserBusiness(models.Model):
    USER_TYPE_CHOICES = (('superuser', 'Superuser'), ('admin', 'Admin'), ('user', 'User'))
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='user')
    class Meta:
        unique_together = ('user', 'business')  # email + business_id unique

    def __str__(self):
        return f"{self.business.business_id}.{self.user.email}"



class Record(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(UserBusiness, on_delete=models.SET_NULL, null=True, related_name='records')
    business = models.ForeignKey(Business, on_delete=models.CASCADE, related_name='records')
    description = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True)
    object_id = models.UUIDField(null=True, blank=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    def clean(self):
        if not self.description.strip():
            raise ValidationError("Description cannot be empty.")

    def __str__(self):
        return f"Record by {self.user} for {self.business} at {self.created_at}"

    class Meta:
        verbose_name = "Record"
        verbose_name_plural = "Records"
        indexes = [
            models.Index(fields=['user'], name='idx_record_user'),
            models.Index(fields=['business'], name='idx_record_business'),
            models.Index(fields=['content_type', 'object_id'], name='idx_record_content'),
        ]

qualifications/templates/inbox.html
{% extends 'base.html' %}
{% load static qualifications_filters %}

{% block title %}Inbox{% endblock %}

{% block nav_items %}
    <a href="{% if user.userbusiness.user_type == 'admin' %}{% url 'users:admin_dashboard' %}{% else %}{% url 'qualifications:user_dashboard' %}{% endif %}" class="bg-blue-500 hover:bg-blue-600 px-4 py-2 rounded text-white">Back to Dashboard</a>
{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-6 max-w-7xl">
    <div class="bg-white rounded-lg shadow-md p-6">
        <h2 class="text-2xl font-semibold text-gray-800 mb-6 text-center">Inbox</h2>
        <div class="mb-4 flex justify-start space-x-4">
            <a href="{% url 'qualifications:sent_messages' %}" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">
                View Sent Messages
            </a>
            <a href="{% url 'qualifications:compose_message' %}" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Compose Message
            </a>
        </div>
        <div class="mb-4">
            <input type="text" id="searchInput" placeholder="Search by subject or sender..." aria-label="Search messages" class="w-full py-2 px-4 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500" oninput="filterMessages()">
        </div>
        {% if messages %}
        <div class="mb-6 space-y-2">
            {% for message in messages %}
            <div class="p-4 rounded-lg {% if message.tags == 'success' %}bg-green-100 text-green-700{% else %}bg-red-100 text-red-700{% endif %}">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}
        
        {% if threads %}
        <div class="overflow-x-auto">
            <table class="w-full border-collapse border border-gray-200 rounded-lg" id="messageTable">
                <thead class="bg-gray-100 text-gray-700 text-sm font-semibold uppercase">
                    <tr>
                        <th class="border border-gray-200 p-3 text-left">Subject</th>
                        <th class="border border-gray-200 p-3 text-left">Sender</th>
                        <th class="border border-gray-200 p-3 text-left">Date</th>
                        <th class="border border-gray-200 p-3 text-left">Unread</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-sm">
                    {% for subject, thread in threads.items %}
                    <tr class="hover:bg-gray-50">
                        <td class="border border-gray-200 p-3">
                            <a href="{% url 'qualifications:message_thread' thread_id=thread.latest_message.id %}" class="text-blue-600 hover:text-blue-800">{{ subject }}</a>


                        </td>
                        <td class="border border-gray-200 p-3">
                            From: {{ thread.latest_message.sender.user.full_name|default:thread.latest_message.sender.user.email }}
                        </td>
                        <td class="border border-gray-200 p-3">{{ thread.latest_message.sent_at|date:"Y-m-d H:i" }}</td>
                        <td class="border border-gray-200 p-3">
                            {% if thread.unread_count > 0 %}
                            <span class="bg-red-500 text-white text-xs font-medium px-2.5 py-0.5 rounded-full">{{ thread.unread_count }}</span>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="text-gray-600 text-center mt-4">No messages received.</p>
        {% endif %}
    </div>
</div>

<script>
function filterMessages() {
    const searchInput = document.getElementById('searchInput').value.toLowerCase();
    const rows = document.querySelectorAll('#messageTable tbody tr');

    rows.forEach(row => {
        const subject = row.cells[0].textContent.toLowerCase();
        const sender = row.cells[1].textContent.toLowerCase();
        
        if (subject.includes(searchInput) || sender.includes(searchInput)) {
            row.style.display = '';
        } else {
            row.style.display = 'none';
        }
    });
}
</script>
{% endblock %}

qualifications/templates/learner_specific_docs_by_assessor.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Upload Learner Files - {{ qualification.qualification_title }}{% endblock %}

{% block nav_items %}
    {% if user_role == 'assessor' %}
    <a href="{% url 'qualifications:assessor_feedback' qualification.id learner.id %}" class="bg-blue-500 hover:bg-blue-600 px-4 py-2 rounded text-white">Back</a>
    {% elif user_role == 'iqa' %}
    <a href="{% url 'qualifications:iqa_view' qualification.id %}" class="bg-blue-500 hover:bg-blue-600 px-4 py-2 rounded text-white">Back</a>
    {% else %}
    <a href="{% url 'qualifications:eqa_view' qualification.id learner.id %}" class="bg-blue-500 hover:bg-blue-600 px-4 py-2 rounded text-white">Back</a>
    {% endif %}
{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <!-- Qualification and Learner Details -->
    <div class="bg-white p-6 rounded-lg shadow-md mb-8">
        <h2 class="text-2xl font-semibold text-gray-800 mb-4">{{ qualification.qualification_title }}</h2>
        <p class="text-gray-600 mb-2"><strong>Learner:</strong> {{ learner_name|default:"Unknown" }}</p>
        <p class="text-gray-600 mb-2"><strong>Institute:</strong> {{ business.name }} (ID: {{ business.business_id }})</p>
    </div>

    <!-- Messages -->
    {% if messages %}
    <div class="mb-6 space-y-2">
        {% for message in messages %}
        <div class="p-4 rounded-lg {% if message.tags == 'success' %}bg-green-100 text-green-700{% elif message.tags == 'warning' %}bg-yellow-100 text-yellow-700{% else %}bg-red-100 text-red-700{% endif %}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <!-- Upload Form -->
    <div class="bg-white p-6 rounded-lg shadow-md mb-8">
        <h3 class="text-xl font-semibold text-gray-800 mb-4">Upload New File</h3>
        <form method="post" enctype="multipart/form-data" action="{% url 'qualifications:learner_specific_docs' qualification.id learner.id %}" class="space-y-4" id="uploadForm">
            {% csrf_token %}
            
            <div>
                <label for="id_title" class="block text-sm font-medium text-gray-700">Title</label>
                <input type="text" name="title" id="id_title" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" required>
            </div>

            <div>
                <label for="id_description" class="block text-sm font-medium text-gray-700">Description</label>
                <textarea name="description" id="id_description" rows="3" class="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"></textarea>
            </div>

            <div>
                <label for="id_file" class="block text-sm font-medium text-gray-700">File</label>
                <input type="file" name="file" id="id_file" class="mt-1 block w-full text-sm text-gray-900 border border-gray-300 rounded-md cursor-pointer bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>

            <div class="flex justify-end space-x-4">
                <button type="submit" class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Submit</button>
            </div>

            <!-- Progress Bar -->
            <div id="uploadProgressContainer" class="hidden mt-4">
                <progress id="uploadProgress" max="100" value="0" class="w-full h-5 rounded-md overflow-hidden"></progress>
                <div id="uploadProgressText" class="text-center font-semibold text-blue-600 mt-1"></div>
            </div>
        </form>
    </div>

    <!-- Existing Files -->
    <div class="bg-white p-6 rounded-lg shadow-md">
        <h3 class="text-xl font-semibold text-gray-800 mb-4">Uploaded Files</h3>
        {% if documents %}
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white border">
                <thead>
                    <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                        <th class="py-3 px-6 text-left">Title</th>
                        <th class="py-3 px-6 text-left">Description</th>
                        <th class="py-3 px-6 text-left">File</th>
                        <th class="py-3 px-6 text-left">Uploaded By</th>
                        <th class="py-3 px-6 text-left">Uploaded At</th>
                        <th class="py-3 px-6 text-left">Actions</th>
                    </tr>
                </thead>
                <tbody class="text-gray-600 text-sm">
                    {% for doc in documents %}
                    <tr class="border-b border-gray-200 hover:bg-gray-100">
                        <td class="py-3 px-6">{{ doc.title }}</td>
                        <td class="py-3 px-6">{{ doc.description|default:"No description" }}</td>
                        <td class="py-3 px-6">
                            <a href="{{ doc.file.url }}" class="text-blue-600 hover:underline" target="_blank">View File</a>
                        </td>
                        <td class="py-3 px-6">{{ doc.uploaded_by_name }} ({{ doc.uploader_role }})</td>
                        <td class="py-3 px-6">{{ doc.uploaded_at|date:"Y-m-d H:i" }}</td>
                        <td class="py-3 px-6 flex space-x-2">
                            {% if request.user == doc.uploaded_by %}
                            <a href="{% url 'qualifications:edit_learner_doc' qualification.id learner.id doc.id %}" class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-1 px-2 rounded">Edit</a>
                            <form method="post" action="{% url 'qualifications:delete_learner_doc' qualification.id learner.id doc.id %}" class="inline">
                                {% csrf_token %}
                                <button type="submit" onclick="return confirm('Are you sure you want to delete this file?');" class="bg-red-500 hover:bg-red-600 text-white font-bold py-1 px-2 rounded">Delete</button>
                            </form>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="text-gray-600">No files uploaded for this learner.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block extra_scripts %}
<script>
document.addEventListener('DOMContentLoaded', () => {
  const form = document.getElementById('uploadForm');
  const progressContainer = document.getElementById('uploadProgressContainer');
  const progressBar = document.getElementById('uploadProgress');
  const progressText = document.getElementById('uploadProgressText');

  form.addEventListener('submit', function(e) {
    e.preventDefault(); // Prevent default form submission

    const fileInput = form.querySelector('input[type="file"]');
    if (!fileInput || fileInput.files.length === 0) {
      alert('Please select a file to upload.');
      return;
    }

    const formData = new FormData(form);

    const xhr = new XMLHttpRequest();
    xhr.open('POST', form.action);

    // Show progress container
    progressContainer.classList.remove('hidden');
    progressBar.value = 0;
    progressText.textContent = 'Starting upload...';

    // Update progress bar during upload
    xhr.upload.addEventListener('progress', (event) => {
      if (event.lengthComputable) {
        const percent = Math.round((event.loaded / event.total) * 100);
        progressBar.value = percent;
        progressText.textContent = `Uploading: ${percent}%`;
      }
    });

    // When upload is complete
    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        progressText.textContent = 'Upload complete! Reloading...';
        window.location.reload();
      } else {
        progressText.textContent = `Upload failed: ${xhr.statusText}`;
      }
    };

    // Handle network errors
    xhr.onerror = () => {
      progressText.textContent = 'Upload failed due to network error.';
    };

    xhr.send(formData);
  });
});
</script>
{% endblock %}