AssessEEZ/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users.views import (
    login_view, learner_view, eqa_view, iqa_view,
    assessor_view, administrator_view, contact_view,
    pricing_view, privacy_policy_view, user_agreement_view, faq_view
)
from django.views.generic import TemplateView
from django.http import HttpResponse

def health_check(request):
    return HttpResponse("OK", content_type="text/plain")

urlpatterns = [
    path('health/', health_check, name='health_check'),
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('qualifications/', include(('qualifications.urls', 'qualifications'), namespace='qualifications')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('login/', login_view, name='login'),
    path('learner/', learner_view, name='learner'),
    path('eqa/', eqa_view, name='eqa'),
    path('iqa/', iqa_view, name='iqa'),
    path('assessor/', assessor_view, name='assessor'),
    path('administrator/', administrator_view, name='administrator'),
    path('contact/', contact_view, name='contact'),
    path('captcha/', include('captcha.urls')),
    path('pricing/', pricing_view, name='pricing'),
    path('privacy_policy/', privacy_policy_view, name='privacy_policy'),
    path('user_agreement/', user_agreement_view, name='user_agreement'),
    path('faq/', faq_view, name='FAQ'),
    path('api/', include('stripe_payments.urls')),
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   # Serve static files from STATICFILES_DIRS during development
   from django.contrib.staticfiles.urls import staticfiles_urlpatterns
   urlpatterns += staticfiles_urlpatterns()

#if settings.DEBUG:
 #   import debug_toolbar
  #  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   # urlpatterns += [
    #    path('__debug__/', include(debug_toolbar.urls)),
    #]

qualifications/urls.py
from django.urls import path
from . import views


app_name = 'qualifications'

urlpatterns = [
    path('qualifications/', views.QualificationAddEditView.as_view(), name='qualification-list'),
    path('<uuid:qualification_id>/', views.QualificationAddEditView.as_view(), name='qualification-detail'),
    path('qualifications/search/', views.QualificationSearchView.as_view(), name='qualification-search'),
    path('add/api/', views.QualificationAddEditView.as_view(), name='add-qualification-api'),
    path('add/', views.render_add_qualification_view, name='add-qualification'),
    path('edit/<uuid:qualification_id>/', views.QualificationAddEditView.as_view(), name='edit-qualification'), 
    path('edit/', views.edit_qualification_view, name='edit-qualification-html'),  
    path('view/', views.view_qualification_view, name='view-qualification'),
    path('list/', views.QualificationListView.as_view(), name='qualification-list'),
    path('add_user/', views.add_user_role_select, name='add_user'),
    path('add_learner/', views.add_learner, name='add_learner'),
    path('add_assessor/', views.add_assessor, name='add_assessor'),
    path('add_iqa/', views.add_iqa, name='add_iqa'),
    path('add_eqa/', views.add_eqa, name='add_eqa'),
    path('get_learners/', views.get_learners, name='get_learners'),
    path('get_assessors/', views.get_assessors, name='get_assessors'),
    path('get_iqas/', views.get_iqas, name='get_iqas'),
    path('current-users/', views.current_users, name='current_users'),
    path('selected_user/<int:user_id>/<str:role_type>/', views.selected_user, name='selected_user'),
    path('toggle_learner_access/', views.toggle_learner_access, name='toggle_learner_access'),
    path('delete-learner-qualification/', views.delete_learner_qualification, name='delete_learner_qualification'),
    path('edit-user-search/', views.edit_user_search, name='edit_user_search'),
    path('search-users/', views.search_users, name='search_users'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('remove-role-qualification/', views.remove_role_qualification, name='remove_role_qualification'),
    path('change_learner_assessor/', views.change_learner_assessor, name='change_learner_assessor'),
    path('change-learner-iqa/', views.change_learner_iqa, name='change_learner_iqa'),
    path('resources/', views.resources, name='resources'),
    path('resources/folder/<uuid:folder_id>/', views.folder_detail, name='folder_detail'),
    path('resources/add_folder/', views.add_folder, name='add_folder'),
    path('resources/delete_file/', views.delete_file, name='delete_file'),
    path('resources/file/<uuid:file_id>/', views.serve_file, name='serve_file'),
    path('resources/edit_folder/<uuid:folder_id>/', views.edit_folder, name='edit_folder'),
    path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
    path('learner_view/<uuid:qualification_id>/', views.learner_view, name='learner_view'),
    path('learner_evidence/<uuid:qualification_id>/<uuid:learner_id>/<uuid:ac_id>/', views.learner_evidence_view, name='learner_evidence'),
    path('assessor/<uuid:qualification_id>/', views.assessor_view, name='assessor_view'),
    path('assessor_feedback/<uuid:qualification_id>/<uuid:learner_id>/', views.assessor_feedback_view, name='assessor_feedback'),
    path('feedback_history/<uuid:qualification_id>/<uuid:learner_id>/<uuid:lo_id>/', views.feedback_history_view, name='feedback_history'),
    path('notifications/', views.notification_view, name='notification_view'),
    path('iqa/<uuid:qualification_id>/', views.iqa_view, name='iqa_view'),
    path('iqa/<uuid:qualification_id>/learner/<uuid:learner_id>/feedback/', views.iqa_feedback_history_view, name='iqa_feedback_history_view'),
    path('iqa/<uuid:qualification_id>/learner/<uuid:learner_id>/unit/<uuid:unit_id>/feedback/', views.iqa_feedback_view, name='iqa_feedback'),
    path('iqa/<uuid:qualification_id>/learner/<uuid:learner_id>/unit/<uuid:unit_id>/feedback_history/', views.iqa_feedback_history, name='iqa_feedback_history'),
    path('iqa/<uuid:qualification_id>/feedback_to_assessor/', views.iqa_feedback_to_assessor_view, name='iqa_feedback_to_assessor'),
    path('iqa/<uuid:qualification_id>/feedback_to_assessor_records/', views.iqa_feedback_to_assessor_records_view, name='iqa_feedback_to_assessor_records'),
    path('iqa/feedback_to_assessor_records/', views.iqa_feedback_to_assessor_records_view, name='iqa_feedback_to_assessor_records'),
    path('doc_requirement/', views.doc_requirement, name='doc_requirement'),
    path('submit_docs/<uuid:qualification_id>/', views.submit_docs, name='submit_docs'),  
    path('doc_check/<uuid:qualification_id>/<uuid:learner_id>/', views.doc_check, name='doc_check'), 
    path('iqa_submitted_docs/<uuid:qualification_id>/<uuid:learner_id>/', views.iqa_submitted_docs, name='iqa_submitted_docs'),
    path('eqa/<uuid:qualification_id>/<uuid:learner_id>/', views.eqa_view, name='eqa_view'),
    path('eqa_learners/<uuid:qualification_id>/', views.eqa_learner_list, name='eqa_learner_list'),
    path('learners_list/<int:user_business_id>/<str:role_type>/<uuid:qualification_id>/', views.learners_list, name='learners_list'),
    path('iqa_sub_doc_for_eqa/<uuid:qualification_id>/<uuid:learner_id>/', views.iqa_sub_doc_for_eqa, name='iqa_sub_doc_for_eqa'),
    path('qualification/<uuid:qualification_id>/learner_specific_docs/<uuid:learner_id>/', views.learner_specific_docs, name='learner_specific_docs'),
    path('qualification/<uuid:qualification_id>/learner_specific_docs/<uuid:learner_id>/edit/<uuid:doc_id>/', views.edit_learner_doc, name='edit_learner_doc'),
    path('qualification/<uuid:qualification_id>/learner_specific_docs/<uuid:learner_id>/delete/<uuid:doc_id>/', views.delete_learner_doc, name='delete_learner_doc'),
    path('learner_resources/<uuid:qualification_id>/', views.learner_resources_view, name='learner_resources'),
    path('assessor_resources/<uuid:qualification_id>/', views.assessor_resources_view, name='assessor_resources'),
    path('iqa_resources/<uuid:qualification_id>/', views.iqa_resources_view, name='iqa_resources'),
    path('eqa_resources/<uuid:qualification_id>/', views.eqa_resources_view, name='eqa_resources'),
    path('inbox/', views.inbox_view, name='inbox'),
    path('compose/', views.compose_message_view, name='compose_message'),
    #path('thread/<str:subject>/', views.message_thread_view, name='message_thread'),
    #path('thread/<path:subject>/', views.message_thread_view, name='message_thread'),
    path('thread/<uuid:thread_id>/', views.message_thread_view, name='message_thread'),
    path('mark-read/', views.mark_message_read_view, name='mark_message_read'),
    path('get-recipients/', views.get_recipients_by_qualification, name='get_recipients_by_qualification'),
    path('assessor/<uuid:qualification_id>/feedback/<uuid:learner_id>/<uuid:lo_id>/provide/', views.provide_feedback, name='provide_feedback'),
    path('sent/', views.sent_messages_view, name='sent_messages'),
    ]

users/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenRefreshView
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('superadmin/', views.superadmin_view, name='superadmin'),
    path('create_admin/', views.create_admin_view, name='create_admin'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('create_user/', views.create_user_view, name='create_user'),
    path('forgot_password/', views.forgot_password_view, name='forgot_password'),
    path('reset_password/<str:uidb64>/<str:token>/', views.reset_password_view, name='reset_password'),
    path('api/token/', views.CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', RedirectView.as_view(pattern_name='login'), name='home'),
    path('logout/', views.custom_logout_view, name='custom_logout'),
    path('business/<str:business_id>/', views.business_details, name='business_details'),
    path('business/<str:business_id>/<str:role>/<str:period>/', views.admin_users_details, name='admin_users_details'),
    path('add_logo/', views.add_logo_view, name='add_logo'),
    path('password-reset-redirect/<str:uidb64>/<str:token>/', views.password_reset_redirect, name='password_reset_redirect'),
    path('superadmin/assign/<uuid:qual_id>/', views.assign_qualification, name='assign_qualification'),
    path('superadmin/dashboard/', views.superadmin_qualifications_dashboard, name='superadmin_qualifications_dashboard'),
    path('main/', views.main_page, name='main_page'),
    path('select_business/', views.select_business, name='select_business'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}AssessEEZ{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'favicon-32x32.png' %}" sizes="32x32">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">
    <style>
        footer * {
            margin: 0 !important;
            padding: 0 !important;
        }
        footer img {
            display: block !important;
            max-width: 100% !important;
            height: auto !important;
        }
        footer p {
            line-height: 1 !important;
            line-height: 1.5 !important;
            margin: 0 !important;
            padding: 0 !important;
        }
        .container {
            max-width: none !important;
        }
        .header-logo {
            border: 3px solid #020920; /* Navy blue border */
        }
        .footer-content-center {
            position: absolute;
            left: 50%;
            transform: translateX(-50%);
        }
    </style>
</head>
<body class="flex flex-col min-h-screen">
    <!-- Header -->
    <header class="bg-blue-600 text-white p-4 shadow-md">
        <div class="container mx-auto flex justify-between items-center">
            <a href="{% url 'home' %}" class="text-xl font-bold">
                <img src="{% static 'images/assesseez_logo.png' %}" alt="AssessEEZ Logo" class="h-14 w-14 header-logo object-contain">
            </a>
            <div class="flex items-center space-x-4">
                {% if request.user.is_authenticated %}
                    <span>Welcome, {{ full_name|default:request.user.email }}</span>
                    <a href="{% url 'qualifications:inbox' %}" class="relative">
                        <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
                        </svg>
                        {% if unread_count > 0 %}
                            <span class="absolute -top-2 -right-2 bg-red-500 text-white text-xs font-medium px-2 py-0.5 rounded-full">{{ unread_count }}</span>
                        {% endif %}
                    </a>
                    {% block nav_items %}
                    {% endblock %}
                    <form method="post" action="{% url 'users:custom_logout' %}" class="inline">
                        {% csrf_token %}
                        <button type="submit" class="bg-red-500 hover:bg-red-600 px-4 py-2 rounded text-white">Logout</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </header>

    <div class="mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="bg-blue-400 text-gray-800 py-4 px-6 mt-auto relative">
        <div class="container mx-auto flex justify-between items-center">
            <div class="flex-1"></div> <!-- Spacer to push content to center -->
            <div class="footer-content-center flex flex-col items-center space-y-2">
                <div class="text-sm">
                    <a href="{% url 'privacy_policy' %}" class="underline hover:text-gray-600 font-medium">Privacy Policy</a> | 
                    <a href="{% url 'user_agreement' %}" class="underline hover:text-gray-600 font-medium">User Agreement</a>
                </div>
                <p class="text-xs text-center">© {% now "Y" %} Paradigm Qualifications Ltd. All rights reserved. Company number 14078939 Registered in England and Wales</p>
            </div>
            <div class="flex-1 flex justify-end">
                <img src="{% if business and business.logo and business.logo.url %}{{ business.logo.url }}{% else %}{% static 'images/assesseez_logo.png' %}{% endif %}" 
                     alt="{% if business and business.name %}{{ business.name }}{% else %}AssessEEZ{% endif %} Logo" 
                     class="h-14 w-14 header-logo object-contain" style="margin-left: 10px; margin-right: 10px;">
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    {% block extra_js %}
    {% endblock %}
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html>
<head>
    <title>reCAPTCHA Test</title>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>
<body>
    <div class="g-recaptcha" data-sitekey="6LcbqVgrAAAAAMwExjT9QvTJdxj00a1Zx0XIB9htQ"></div>
</body>
</html>